// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const databaseUrl = env("DATABASE_URL");
const shadowDatabaseUrl = databaseUrl
  .replace(/\/([^/?]+)(\?|$)/u, (_m, dbName: string, suffix: string) => `/${dbName}_shadow${suffix}`)
  .replace(/schema=[^&]+/u, "schema=public");

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npm run db:seed", // seed命令配置
  },
  datasource: {
    url: databaseUrl,
    shadowDatabaseUrl,
  },
});
